### PR TITLE
Research on motor mount design

### LINKED ISSUE #14: Research on motor mount design

### PR DESCRIPTION
**Pull request by MwadimeOnyango**
Resolves #14. Did research on potential motor mount designs

### CODE REVIEW

**Comment by rodneyosodo** [comment]
@MwadimeOnyango Have a look at this regarding your PR title https://gist.github.com/mikepea/863f63d6e37281e329f8

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Remove `.txt` file. We use markdown for documentations

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
@MwadimeOnyango Can you add some reference designs?

**Comment by rodneyosodo** [comment]
It is okay to put `.png` and `.jpeg` files. An iam file isn't needed

**Comment by rodneyosodo** [comment]
Here is an [example](https://github.com/nakujaproject/airframeN3/blob/main/Progress/02recoveryMechanism.md)

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Reference and display the images on the research. Also add this report to the research directory. You can create a sub folder for images called `img` or `assets`

**Comment by MwadimeOnyango** [comment]
The images are mine i.e. I drew them. WHat's the protocol on that

**Pull request merged**
